import "./globals.css";
import type { Metadata } from "next";
import { fc_ekaluckbold, fc_ekaluckregular, Helvetica } from "@utils/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={` ${fc_ekaluckbold.variable} ${fc_ekaluckregular.variable} ${Helvetica.variable}  `}
    >
      <body>{children}</body>
    </html>
  );
}
